AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Função responsável por listar os aeroportos de origem e de destino para então
  salvar as rotas
Resources:
  airport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        Função responsável por listar os aeroportos de origem e de destino para
        então salvar as rotas
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::564384903856:role/service-role/airport'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /airport
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint
