AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Esta função é responsável pelo cadastro do pacote que será transportado, e
  conterá informações como origem, destino, peso, volume, valor, entre outros.
  Ela também será responsável por encontrar os passageiros que farão o mesmo
  percusso
Resources:
  package:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        Esta função é responsável pelo cadastro do pacote que será transportado,
        e conterá informações como origem, destino, peso, volume, valor, entre
        outros. Ela também será responsável por encontrar os passageiros que
        farão o mesmo percusso
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::564384903856:role/service-role/package'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /package
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint
